const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
const xml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const locales={Hindi:'hi-IN',English:'en-IN',Hinglish:'hi-IN',Gujarati:'gu-IN',Marathi:'mr-IN',Punjabi:'pa-IN',Bengali:'bn-IN',Tamil:'ta-IN',Telugu:'te-IN',Malayalam:'ml-IN',Kannada:'kn-IN',Urdu:'ur-IN'};
export function providers({env=process.env,request=fetch}={}){
 const otpReady=()=>!!(env.TWILIO_ACCOUNT_SID&&env.TWILIO_AUTH_TOKEN&&env.TWILIO_VERIFY_SERVICE_SID);
 const voiceReady=()=>!!(env.AZURE_SPEECH_ENDPOINT&&env.AZURE_SPEECH_KEY);
 async function verifyCall(action,params){if(!otpReady())fail(503,'SMS OTP provider is not configured.');if(!/^VA[a-fA-F0-9]{32}$/.test(env.TWILIO_VERIFY_SERVICE_SID))fail(503,'OTP service configuration is invalid.');const response=await request('https://verify.twilio.com/v2/Services/'+env.TWILIO_VERIFY_SERVICE_SID+'/'+action,{method:'POST',headers:{Authorization:'Basic '+Buffer.from(env.TWILIO_ACCOUNT_SID+':'+env.TWILIO_AUTH_TOKEN).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params),signal:AbortSignal.timeout(20000)});if(!response.ok){if([400,404,429].includes(response.status))fail(response.status===429?429:400,'OTP request could not be completed. Check the number/code or request a new code.');fail(502,'OTP provider unavailable.');}return response.json();}
 async function sendOtp(phone){const result=await verifyCall('Verifications',{To:phone,Channel:'sms'});if(result.status!=='pending'||!result.sid)fail(502,'OTP provider did not accept the request.');return {sid:result.sid};}
 async function checkOtp(sid,code){const result=await verifyCall('VerificationCheck',{VerificationSid:sid,Code:code});return result.status==='approved';}
 function speechEndpoint(){if(!voiceReady())fail(503,'Speech provider is not configured.');const endpoint=new URL(env.AZURE_SPEECH_ENDPOINT);if(endpoint.protocol!=='https:'||!endpoint.hostname.endsWith('.cognitiveservices.azure.com')||endpoint.username||endpoint.password)fail(503,'Use the HTTPS Azure Speech resource endpoint.');return endpoint.origin;}
 let voiceCache=null,voiceCacheAt=0;
 async function voices(){if(voiceCache&&Date.now()-voiceCacheAt<3600000)return voiceCache;const response=await request(speechEndpoint()+'/tts/cognitiveservices/voices/list',{headers:{'Ocp-Apim-Subscription-Key':env.AZURE_SPEECH_KEY},signal:AbortSignal.timeout(20000)});if(!response.ok)fail(502,'Could not retrieve the speech voice catalog.');const body=await response.json();if(!Array.isArray(body))fail(502,'Invalid voice catalog.');voiceCache=body;voiceCacheAt=Date.now();return body;}
 async function speech(b){if(!String(b.script||'').trim()||String(b.script).length>5000)fail(400,'Enter a script of 1–5000 characters.');const all=await voices(),locale=locales[b.language]||b.language;const gender=b.gender||'Female';const voice=all.find(v=>v.Locale===locale&&v.Gender===gender&&(!b.voiceId||v.ShortName===b.voiceId));if(!voice)fail(400,'No matching voice is available for this language and gender.');
  const styleMap={Soft:'gentle',Hard:'shouting',Serious:'serious','Breaking News':'newscast',Energetic:'excited',Calm:'calm',Emotional:'sad',Tense:'terrified',Reporter:'newscast',Anchor:'newscast'};const style=b.style==='Professional'||!b.style?null:styleMap[b.style];if(b.style&&b.style!=='Professional'&&(!style||!voice.StyleList?.includes(style)))fail(400,'This voice does not support the selected style. Choose Professional or a supported voice.');
  const clamp=(x,min,max,defaultValue)=>Number.isFinite(Number(x))?Math.max(min,Math.min(max,Number(x))):defaultValue;
  const speed=Math.round((clamp(b.speed,.5,2,1)-1)*100),pitch=Math.round((clamp(b.pitch,.5,2,1)-1)*50),volume=Math.round(clamp(b.volume,0,1,1)*100);
  let text=`<prosody rate="${speed>=0?'+':''}${speed}%" pitch="${pitch>=0?'+':''}${pitch}%" volume="${volume}">${xml(b.script)}</prosody>`;if(style)text=`<mstts:express-as style="${style}">${text}</mstts:express-as>`;
  const ssml=`<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="https://www.w3.org/2001/mstts" xml:lang="${xml(voice.Locale)}"><voice name="${xml(voice.ShortName)}">${text}</voice></speak>`;
  const response=await request(speechEndpoint()+'/cognitiveservices/v1',{method:'POST',headers:{'Ocp-Apim-Subscription-Key':env.AZURE_SPEECH_KEY,'Content-Type':'application/ssml+xml','X-Microsoft-OutputFormat':'audio-24khz-96kbitrate-mono-mp3','User-Agent':'DMS-NEWS'},body:ssml,signal:AbortSignal.timeout(45000)});if(!response.ok)fail(502,'Speech generation failed.');const audio=Buffer.from(await response.arrayBuffer());if(audio.length>16*1024*1024||!audio.length)fail(502,'Invalid speech output.');return {audio,voice:voice.ShortName,style:style||'neutral',language:voice.Locale};
 }
 return {otpReady,voiceReady,sendOtp,checkOtp,voices,speech};
}
