import http from 'node:http';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {promisify} from 'node:util';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {connect} from './db.mjs';
import * as seed from './seed.mjs';
import {mediaEngine} from './media.mjs';
import {providers} from './providers.mjs';
import {Readable} from 'node:stream';
const provider=providers();
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const dir=path.resolve(process.env.DATA_DIR||path.join(root,'backend/data'));
fs.mkdirSync(path.join(dir,'files'),{recursive:true});
const db=await connect(dir); await db.exec(fs.readFileSync(path.join(root,'backend/schema.sql'),'utf8'));
const uid=()=>crypto.randomUUID(), now=()=>new Date().toISOString();
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const scrypt=promisify(crypto.scrypt);
async function passwordHash(p){const salt=crypto.randomBytes(16).toString('hex');return salt+':'+(await scrypt(p,salt,64)).toString('hex');}
async function verifyPassword(p,h){const [s,k]=h.split(':');return crypto.timingSafeEqual(await scrypt(p,s,64),Buffer.from(k,'hex'));}
const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
const safeUser=u=>({id:u.id,email:u.email.endsWith('@phone.dms.invalid')?null:u.email,mobile:u.phone||null,name:u.name,role:u.role,active:!!u.active,created:u.created});
async function audit(actor,action,target){await db.run('INSERT INTO audit_logs VALUES(?,?,?,?,?)',uid(),actor,action,target,now());}
async function put(kind,id,body,owner=''){await db.run('INSERT INTO records(kind,id,owner,body,updated) VALUES(?,?,?,?,?) ON CONFLICT(kind,id) DO UPDATE SET body=excluded.body,updated=excluded.updated',kind,id,owner,JSON.stringify({...body,id}),now());}
async function get(kind,id){const r=await db.get('SELECT body FROM records WHERE kind=? AND id=?',kind,id);return r?JSON.parse(r.body):null;}
async function list(kind,owner){const a=owner===undefined?await db.all('SELECT body FROM records WHERE kind=?',kind):await db.all('SELECT body FROM records WHERE kind=? AND owner=?',kind,owner);return a.map(r=>JSON.parse(r.body));}
const media=mediaEngine({dir,db,put,list});
if(!(await get('settings','app'))){for(const p of seed.plans)await put('plans',p.id,p);for(const t of seed.templates)await put('templates',t.id,t);await put('settings','app',seed.settings);}
if(process.argv.includes('--create-admin')){
 const email=String(process.env.ADMIN_EMAIL||'').toLowerCase().trim(),p=process.env.ADMIN_PASSWORD||'';
 if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)||p.length<12)fail(400,'Set ADMIN_EMAIL and ADMIN_PASSWORD (12+ characters) in environment.');
 if(await db.get('SELECT id FROM users WHERE email=?',email))fail(409,'Account exists; no automatic privilege changes.');
 await db.run('INSERT INTO users VALUES(?,?,?,?,?,?,?)',uid(),email,'DMS Administrator',await passwordHash(p),'admin',1,now());console.log('Administrator created. Remove bootstrap environment values.');process.exit(0);
}
const hits=new Map();
function rate(req,key,limit=100){const ip=req.socket.remoteAddress||'';const k=ip+key;const t=Date.now();const a=hits.get(k)||{n:0,t};if(t-a.t>60000){a.n=0;a.t=t;}a.n++;hits.set(k,a);if(a.n>limit)fail(429,'Too many requests. Try again in one minute.');}
setInterval(()=>{for(const[k,v]of hits)if(Date.now()-v.t>120000)hits.delete(k);},60000).unref();
async function body(req){let n=0,a=[];for await(const x of req){n+=x.length;if(n>18*1024*1024)fail(413,'Request too large (18 MB maximum).');a.push(x);}const raw=Buffer.concat(a);try{return {raw,data:raw.length?JSON.parse(raw):{}};}catch{fail(400,'Invalid JSON');}}
async function auth(req){const name=req.url.startsWith('/api/admin')?'dms_admin_session':'dms_session';const cookie=(req.headers.cookie||'').split(/;\s*/).find(x=>x.startsWith(name+'='))?.slice(name.length+1);const bearer=req.headers.authorization?.match(/^Bearer (.+)$/)?.[1];const token=bearer||cookie;if(!token)fail(401,'Please log in.');const s=await db.get('SELECT user_id FROM sessions WHERE token=? AND expires>?',hash(token),now());const u=s&&await db.get('SELECT users.*,phone_identities.phone FROM users LEFT JOIN phone_identities ON phone_identities.user_id=users.id WHERE users.id=?',s.user_id);if(!u||!u.active)fail(401,'Session expired or account disabled.');return u;}
function admin(u){if(u.role!=='admin')fail(403,'Administrator access required.');}
async function entitlement(u){const sub=await db.get('SELECT * FROM subscriptions WHERE user_id=? AND expires>?',u.id,now());const plan=await get('plans',sub?.plan_id||'free');if(!plan)fail(403,'Plan unavailable.');const start=sub?.starts||new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString();const counts=await db.all('SELECT kind,COUNT(*) AS count FROM usage_events WHERE user_id=? AND created>=? GROUP BY kind',u.id,start);return {plan,subscription:sub||null,usage:Object.fromEntries(counts.map(x=>[x.kind,Number(x.count)]))};}
const locks=new Map();
async function locked(key,fn){const old=locks.get(key)||Promise.resolve();let release;const gate=new Promise(r=>release=r);const chain=old.then(()=>gate);locks.set(key,chain);await old;try{return await fn();}finally{release();if(locks.get(key)===chain)locks.delete(key);}}
async function quota(u,kind){const e=await entitlement(u),limit=e.plan[kind==='voice'?'voiceLimit':'exportLimit'];if((e.usage[kind]||0)>=limit)fail(403,'Your plan limit has been reached.');const id=uid();await db.run('INSERT INTO usage_events VALUES(?,?,?,?)',id,u.id,kind,now());return {e,id};}
function validate(kind,b,id){if(!b||typeof b!=='object'||Array.isArray(b))fail(400,'Expected an object.');if(kind==='plans'){for(const k of ['price','days','voiceLimit','exportLimit','resolution'])if(!Number.isInteger(b[k])||b[k]<0)fail(400,'Invalid '+k);if(b.days<1||![720,1080].includes(b.resolution))fail(400,'Invalid duration or resolution.');for(const key of ['premium','watermark','active'])if(typeof b[key]!=='boolean')fail(400,'Invalid '+key);if(id==='free'&&(b.price!==0||!b.active))fail(400,'Free plan must remain active and free.');if(id!=='free'&&b.active&&b.price<100)fail(400,'An active paid plan requires a price of at least ₹1.');}if(['plans','templates','coupons'].includes(kind)&&(!b.name||String(b.name).length>120))fail(400,'Name is required (maximum 120 characters).');if(kind==='templates'&&!['16:9','9:16','1:1','4:5'].includes(b.format))fail(400,'Unsupported format.');if(kind==='templates'){if(typeof b.active!=='boolean'||typeof b.premium!=='boolean'||!/^#[0-9a-f]{6}$/i.test(b.color||''))fail(400,'Invalid template options.');for(const k of ['publishAt','expiresAt'])if(b[k]){if(!Number.isFinite(Date.parse(b[k])))fail(400,'Invalid schedule');b[k]=new Date(b[k]).toISOString();}if(b.publishAt&&b.expiresAt&&b.expiresAt<=b.publishAt)fail(400,'Expiry must follow publication.');if(b.background){if(!/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(b.background))fail(400,'Upload a PNG or JPEG image.');const image=Buffer.from(b.background.split(',')[1],'base64');if(image.length>4*1024*1024||!(image.subarray(0,8).toString('hex')==='89504e470d0a1a0a'||image.subarray(0,3).toString('hex')==='ffd8ff'))fail(400,'Invalid template image.');}}if(kind==='settings'){if(typeof b.maintenance!=='boolean'||!Array.isArray(b.languages)||!Array.isArray(b.categories)||!Array.isArray(b.festivals))fail(400,'Invalid application settings.');}return {...b,id};}
async function razor(route,data){if(!process.env.RAZORPAY_KEY_ID||!process.env.RAZORPAY_KEY_SECRET)fail(503,'Razorpay is not configured.');const r=await fetch('https://api.razorpay.com/v1/'+route,{method:data?'POST':'GET',headers:{Authorization:'Basic '+Buffer.from(process.env.RAZORPAY_KEY_ID+':'+process.env.RAZORPAY_KEY_SECRET).toString('base64'),'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(20000)});if(!r.ok)fail(502,'Payment provider request failed.');return r.json();}
function validSig(input,sig,secret){if(!secret||!/^[0-9a-f]{64}$/i.test(sig||''))return false;const actual=crypto.createHmac('sha256',secret).update(input).digest();return crypto.timingSafeEqual(actual,Buffer.from(sig,'hex'));}
async function settle(order,payment){return locked('payment:'+order.user_id,()=>db.transaction(async tx=>{
 const current=await tx.get('SELECT * FROM payments WHERE id=?'+(process.env.DATABASE_URL?' FOR UPDATE':''),order.id);if(current.status==='paid')return;
 if(payment.order_id!==order.id||payment.status!=='captured'||payment.amount!==order.amount||payment.currency!==order.currency)fail(400,'Payment details do not match a captured order.');
 const snapshot=JSON.parse(order.plan_snapshot);const existing=await tx.get('SELECT * FROM subscriptions WHERE user_id=?',order.user_id);const starts=now();const base=existing?.plan_id===order.plan_id?Math.max(Date.now(),Date.parse(existing.expires)):Date.now();const expires=new Date(base+snapshot.days*86400000).toISOString();
 await tx.run('INSERT INTO subscriptions VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET plan_id=excluded.plan_id,starts=excluded.starts,expires=excluded.expires',order.user_id,order.plan_id,starts,expires);
 await tx.run('UPDATE payments SET status=?,provider_payment_id=? WHERE id=?','paid',payment.id,order.id);
 await tx.run('INSERT INTO audit_logs VALUES(?,?,?,?,?)',uid(),order.user_id,'payment.captured',order.id,now());
}));}

async function ffmpeg(args){return new Promise((resolve,reject)=>{const p=spawn('ffmpeg',['-hide_banner','-loglevel','error','-y',...args]);let err='';p.stderr.on('data',b=>err+=b.toString().slice(0,1000));const timer=setTimeout(()=>p.kill('SIGKILL'),90000);p.on('error',reject);p.on('close',c=>{clearTimeout(timer);c===0?resolve():reject(new Error('Media render failed: '+err.slice(0,250)));});});}
function decodeImage(s){if(typeof s!=='string'||!s.startsWith('data:image/png;base64,'))fail(400,'A PNG canvas image is required.');const b=Buffer.from(s.split(',')[1],'base64');if(b.length<24||b.length>12*1024*1024||b.subarray(0,8).toString('hex')!=='89504e470d0a1a0a'||b.readUInt32BE(16)>4096||b.readUInt32BE(20)>4096)fail(400,'Invalid or oversized PNG.');return b;}
let jobs=0;
async function render(u,b){if(jobs>=2)fail(429,'Render queue busy. Try again shortly.');if(!['png','jpg','mp4'].includes(b.format))fail(400,'Unsupported export format.');const png=decodeImage(b.image);if(b.templateId){const t=await get('templates',b.templateId);if(!t||!t.active||(t.publishAt&&t.publishAt>now())||(t.expiresAt&&t.expiresAt<=now()))fail(404,'Template unavailable.');const e=await entitlement(u);if(t.premium&&!e.plan.premium)fail(403,'Premium template requires a premium plan.');}
 const {e,id:usageId}=await locked(u.id,()=>quota(u,'export'));const id=uid(),input=path.join(dir,'files',id+'.source.png'),output=path.join(dir,'files',id+'.'+b.format);await locked('render-slot',async()=>{if(jobs>=2){await db.run('DELETE FROM usage_events WHERE id=?',usageId);fail(429,'Render queue busy. Try again shortly.');}jobs++;});
 try{await fsp.writeFile(input,png);const vertical=png.readUInt32BE(20)>png.readUInt32BE(16);const scale=vertical?`scale=${e.plan.resolution}:-2`:`scale=-2:${e.plan.resolution}`;const watermark=e.plan.watermark?",drawtext=text='Created with DMS NEWS':fontcolor=white:fontsize=22:box=1:boxcolor=black@0.7:x=w-tw-24:y=h-th-20":'';
 const args=b.format==='mp4'?['-loop','1','-i',input,'-t',String(Math.min(60,Math.max(1,Number(b.duration)||15))),'-vf',scale+watermark,'-c:v','libx264','-preset','ultrafast','-pix_fmt','yuv420p','-r','25','-movflags','+faststart',output]:['-i',input,'-vf',scale+watermark,'-frames:v','1',output];if(b.format==='mp4'&&(b.timeline||b.clips?.length||b.narrationId||b.musicId||b.introId||b.outroId)){await media.compose(u,b,input,output,e.plan,png);}else await ffmpeg(args);
 await put('downloads',id,{id,name:String(b.name||'DMS News').slice(0,120),format:b.format,created:now(),url:'/api/files/'+id+'.'+b.format},u.id);return {id,url:'/api/files/'+id+'.'+b.format};
 }catch(err){await fsp.unlink(output).catch(()=>{});await db.run('DELETE FROM usage_events WHERE id=?',usageId);throw err;}finally{jobs--;await fsp.unlink(input).catch(()=>{});}}
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.jpeg':'image/jpeg','.jpg':'image/jpeg','.png':'image/png','.mp4':'video/mp4','.json':'application/json'};
async function serve(res,p){const stat=await fsp.stat(p).catch(()=>null);if(!stat?.isFile())fail(404,'File not found.');res.writeHead(200,{'Content-Type':MIME[path.extname(p)]||'application/octet-stream','Content-Length':stat.size});fs.createReadStream(p).pipe(res);}
const server=http.createServer(async(req,res)=>{
 const send=(status,data,headers={})=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store',...headers});res.end(JSON.stringify(data));};
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','same-origin');
 try{
 const url=new URL(req.url,'http://localhost'),p=url.pathname;rate(req,'all',180);
 if(!p.startsWith('/api/')){if(p.startsWith('/assets/')&&p!=='/assets/logo.jpeg')fail(404,'Not found.');const rel=p==='/admin'||p==='/admin/'?'admin/index.html':p.startsWith('/admin/')?p.slice(1):p==='/'?'web/index.html':p.startsWith('/assets/')?p.slice(1):'web/'+p.slice(1);const file=path.resolve(root,rel);if(!file.startsWith(root+'/web/')&&!file.startsWith(root+'/assets/')&&!file.startsWith(root+'/admin/'))fail(404,'Not found.');return await serve(res,file);}
 if(!['GET','HEAD'].includes(req.method)&&req.headers.origin&&req.headers.origin!==(process.env.PUBLIC_ORIGIN||'http://localhost:8080'))fail(403,'Origin not allowed.');
 if(p==='/api/health')return send(200,{ok:true,version:'0.3.0',database:process.env.DATABASE_URL?'postgresql':'sqlite'});
 if(p==='/api/config'&&req.method==='GET'){const settings=await get('settings','app');return send(200,{settings,plans:(await list('plans')).filter(x=>x.active||x.id!=='free'),templates:(await list('templates')).filter(x=>x.active&&(!x.publishAt||x.publishAt<=now())&&(!x.expiresAt||x.expiresAt>now())),capabilities:{ai:!!process.env.AI_ADAPTER_URL,voice:provider.voiceReady()||!!process.env.AI_ADAPTER_URL,otp:provider.otpReady(),payment:!!process.env.RAZORPAY_KEY_ID,video:'timeline-mp4'}});}
 if(p==='/api/payments/webhook'&&req.method==='POST'){const {raw,data}=await body(req);if(!validSig(raw,req.headers['x-razorpay-signature'],process.env.RAZORPAY_WEBHOOK_SECRET))fail(401,'Invalid webhook signature.');if(data.event==='payment.captured'){const payment=data.payload?.payment?.entity;const order=payment&&await db.get('SELECT * FROM payments WHERE id=?',payment.order_id);if(order)await settle(order,payment);}return send(200,{ok:true});}
 if(p==='/api/auth/otp/send'&&req.method==='POST'){rate(req,'otp-send',5);if(!provider.otpReady())fail(503,'SMS OTP provider is not configured.');const {data:b}=await body(req);const phone=String(b.phone||'').trim();if(!/^\+[1-9]\d{7,14}$/.test(phone))fail(400,'Use an international mobile number, for example +91 followed by 10 digits.');const result=await locked('otp-phone:'+hash(phone),async()=>{const last=await get('otp_rate',hash(phone));if(last&&Date.now()-last.at<60000)fail(429,'Please wait 60 seconds before requesting another code.');await put('otp_rate',hash(phone),{at:Date.now()});const v=await provider.sendOtp(phone);const id=uid();await put('otp_challenge',id,{phone,sid:v.sid,attempts:0,expires:Date.now()+600000});return {challengeId:id,expiresIn:600};});return send(200,result);}
 if(p==='/api/auth/otp/check'&&req.method==='POST'){rate(req,'otp-check',10);const {data:b}=await body(req);if(!/^[a-f0-9-]{36}$/.test(b.challengeId||'')||!/^\d{4,10}$/.test(b.code||''))fail(400,'Enter a valid verification code.');const result=await locked('otp-check:'+b.challengeId,async()=>{const c=await get('otp_challenge',b.challengeId);if(!c||c.expires<Date.now()||c.attempts>=5)fail(401,'OTP expired or attempt limit reached. Request a new code.');await put('otp_challenge',b.challengeId,{...c,attempts:c.attempts+1});if(!await provider.checkOtp(c.sid,b.code))fail(401,'Incorrect verification code.');const token=crypto.randomBytes(32).toString('hex');let person;await db.transaction(async tx=>{const identity=await tx.get('SELECT user_id FROM phone_identities WHERE phone=?',c.phone);if(identity){person=await tx.get('SELECT * FROM users WHERE id=?',identity.user_id);if(!person.active)fail(403,'Account disabled.');}else{person={id:uid(),email:hash(c.phone)+'@phone.dms.invalid',name:String(b.name||'DMS Reporter').slice(0,100),password:await passwordHash(crypto.randomBytes(48).toString('hex')),role:'user',active:1,created:now()};await tx.run('INSERT INTO users VALUES(?,?,?,?,?,?,?)',person.id,person.email,person.name,person.password,'user',1,person.created);await tx.run('INSERT INTO phone_identities VALUES(?,?)',c.phone,person.id);}await tx.run('INSERT INTO sessions VALUES(?,?,?)',hash(token),person.id,new Date(Date.now()+604800000).toISOString());await tx.run('DELETE FROM records WHERE kind=? AND id=?','otp_challenge',b.challengeId);});person.phone=c.phone;await audit(person.id,'auth.otp_login',person.id);return {user:safeUser(person),token};});return send(200,result,{'Set-Cookie':`dms_session=${result.token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${process.env.COOKIE_SECURE==='true'?'; Secure':''}`});}
 if(['/api/auth/register','/api/auth/login','/api/admin-auth/login'].includes(p)&&req.method==='POST'){rate(req,'auth',12);const {data:b}=await body(req);const email=String(b.email||'').toLowerCase().trim(),password=String(b.password||'');if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)||password.length<12||password.length>256)fail(400,'Enter an email and a password of 12–256 characters.');let u=await db.get('SELECT * FROM users WHERE email=?',email);
 if(p.endsWith('register')){if(u)fail(409,'Account already exists.');if(!String(b.name||'').trim())fail(400,'Name required.');u={id:uid(),email,name:String(b.name).trim().slice(0,100),password:await passwordHash(password),role:'user',active:1,created:now()};await db.run('INSERT INTO users VALUES(?,?,?,?,?,?,?)',u.id,u.email,u.name,u.password,u.role,1,u.created);}
 else if(!u||!u.active||!await verifyPassword(password,u.password))fail(401,'Incorrect email or password.');
 if(p==='/api/admin-auth/login')admin(u);const cookieName=p==='/api/admin-auth/login'?'dms_admin_session':'dms_session';const token=crypto.randomBytes(32).toString('hex');await db.run('INSERT INTO sessions VALUES(?,?,?)',hash(token),u.id,new Date(Date.now()+86400000*7).toISOString());await audit(u.id,'auth.login',u.id);return send(200,{user:safeUser(u),token},{'Set-Cookie':`${cookieName}=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${process.env.COOKIE_SECURE==='true'?'; Secure':''}`});}
 const u=await auth(req);const settings=await get('settings','app');if(settings.maintenance&&u.role!=='admin'&&!p.startsWith('/api/auth/'))fail(503,'DMS NEWS is currently being updated. Please check again shortly.');
 if(p==='/api/admin-auth/me'){admin(u);return send(200,{user:safeUser(u)});}
 if(p==='/api/admin-auth/logout'&&req.method==='POST'){admin(u);const token=(req.headers.cookie||'').split(/;\s*/).find(x=>x.startsWith('dms_admin_session='))?.slice(18)||req.headers.authorization?.slice(7);if(token)await db.run('DELETE FROM sessions WHERE token=?',hash(token));return send(200,{ok:true},{'Set-Cookie':'dms_admin_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'});}
 if(p==='/api/auth/logout'&&req.method==='POST'){const token=req.headers.authorization?.slice(7)||(req.headers.cookie||'').split('; ').find(x=>x.startsWith('dms_session='))?.slice(12);if(token)await db.run('DELETE FROM sessions WHERE token=?',hash(token));return send(200,{ok:true},{'Set-Cookie':'dms_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'});}
 if(p==='/api/me'&&req.method==='GET')return send(200,{user:safeUser(u),...await entitlement(u)});
 if(p==='/api/auth/password'&&req.method==='POST'){const {data:b}=await body(req);if(!await verifyPassword(String(b.current||''),u.password)||String(b.password||'').length<12)fail(400,'Current password incorrect or new password too short.');await db.run('UPDATE users SET password=? WHERE id=?',await passwordHash(b.password),u.id);await db.run('DELETE FROM sessions WHERE user_id=?',u.id);return send(200,{ok:true});}
 const own=p.match(/^\/api\/(projects|favourites|support|downloads|notifications)(?:\/([\w-]+))?$/);
 if(own){const[,kind,id]=own;if(req.method==='GET')return send(200,await list(kind,kind==='notifications'?undefined:u.id));if(kind==='downloads'||kind==='notifications')fail(405,'Read only.');if(id){const r=await db.get('SELECT owner FROM records WHERE kind=? AND id=?',kind,id);if(r&&r.owner!==u.id)fail(404,'Not found.');}if(req.method==='DELETE'&&id){await db.run('DELETE FROM records WHERE kind=? AND id=? AND owner=?',kind,id,u.id);return send(200,{ok:true});}if(['POST','PUT'].includes(req.method)){const {data:b}=await body(req);if(JSON.stringify(b).length>8*1024*1024)fail(413,'Project too large.');const key=id||uid();await put(kind,key,{...b,id:key,updated:now()},u.id);return send(200,{id:key});}}
 if(p==='/api/media'&&req.method==='POST'){rate(req,'upload',10);return send(201,await locked('upload:'+u.id,()=>media.upload(req,u,url.searchParams.get('name'))));}
 if(p==='/api/media'&&req.method==='GET')return send(200,await list('media',u.id));
 const mediaMatch=p.match(/^\/api\/media\/([a-f0-9-]{36})$/);if(mediaMatch&&req.method==='DELETE'){const item=await media.owned(u,mediaMatch[1]);if(jobs)fail(409,'Please wait for active renders to finish.');if((await list('projects',u.id)).some(project=>JSON.stringify(project).includes(item.id)))fail(409,'This media is used by a saved project. Remove it from that project first.');await fsp.unlink(item.path).catch(()=>{});await db.run('DELETE FROM records WHERE kind=? AND id=? AND owner=?','media',item.id,u.id);return send(200,{ok:true});}if(mediaMatch&&req.method==='GET'){const item=await media.owned(u,mediaMatch[1]);const bytes=await fsp.readFile(item.path);res.writeHead(200,{'Content-Type':item.mime,'Content-Length':bytes.length,'Cache-Control':'private, no-store'});res.end(bytes);return;}
 if(p.startsWith('/api/files/')){const name=p.slice(11);if(!/^[\w-]+\.(png|jpg|mp4)$/.test(name))fail(404,'File not found.');const record=await db.get('SELECT owner FROM records WHERE kind=? AND id=?','downloads',name.split('.')[0]);if(!record||record.owner!==u.id)fail(404,'File not found.');return await serve(res,path.join(dir,'files',name));}
 if(p==='/api/exports'&&req.method==='POST'){const {data:b}=await body(req);return send(201,await render(u,b));}
 if(p==='/api/payments'&&req.method==='GET')return send(200,await db.all('SELECT id,plan_id,amount,currency,status,created,provider_payment_id FROM payments WHERE user_id=? ORDER BY created DESC',u.id));
 if(p==='/api/payments/order'&&req.method==='POST'){const {data:b}=await body(req);const plan=await get('plans',b.planId);if(!plan||!plan.active||plan.price<=0)fail(400,'Plan is not available for purchase.');const order=await razor('orders',{amount:plan.price,currency:'INR',receipt:uid()});await db.run('INSERT INTO payments VALUES(?,?,?,?,?,?,?,?,?)',order.id,u.id,plan.id,plan.price,'INR','created',null,JSON.stringify(plan),now());return send(201,{orderId:order.id,keyId:process.env.RAZORPAY_KEY_ID,amount:plan.price,currency:'INR'});}
 if(p==='/api/payments/verify'&&req.method==='POST'){const {data:b}=await body(req);const o=await db.get('SELECT * FROM payments WHERE id=? AND user_id=?',b.razorpay_order_id,u.id);if(!o||!validSig(o.id+'|'+b.razorpay_payment_id,b.razorpay_signature,process.env.RAZORPAY_KEY_SECRET))fail(400,'Invalid payment signature.');await settle(o,await razor('payments/'+encodeURIComponent(b.razorpay_payment_id)));return send(200,{ok:true});}
 if(p==='/api/ai/voices'&&req.method==='GET'){const all=await provider.voices();return send(200,all.map(v=>({id:v.ShortName,language:v.Locale,gender:v.Gender,styles:v.StyleList||[]})));}
 if(p==='/api/ai/voice'&&req.method==='POST'&&provider.voiceReady()){rate(req,'ai',10);const {data:b}=await body(req);const reservation=await locked(u.id,()=>quota(u,'voice'));try{const speech=await provider.speech(b);const stream=Readable.from([speech.audio]);stream.headers={'content-type':'audio/mpeg'};const saved=await locked('upload:'+u.id,()=>media.upload(stream,u,'DMS voice '+now()+'.mp3'));return send(200,{audioUrl:saved.url,mediaId:saved.id,voice:speech.voice,style:speech.style,language:speech.language});}catch(e){await db.run('DELETE FROM usage_events WHERE id=?',reservation.id);throw e;}}
 if(['/api/ai/script','/api/ai/voice'].includes(p)&&req.method==='POST'){if(!process.env.AI_ADAPTER_URL)fail(503,'AI provider is not configured.');rate(req,'ai',10);const {data:b}=await body(req);if(JSON.stringify(b).length>16000)fail(400,'AI input is too long.');const kind=p.endsWith('voice')?'voice':'script';const reservation=kind==='voice'?await locked(u.id,()=>quota(u,'voice')):null;try{const r=await fetch(process.env.AI_ADAPTER_URL.replace(/\/$/,'')+'/'+kind,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+(process.env.AI_ADAPTER_TOKEN||'')},body:JSON.stringify(b),signal:AbortSignal.timeout(45000)});if(!r.ok)fail(502,'AI provider failed.');return send(200,await r.json());}catch(e){if(reservation)await db.run('DELETE FROM usage_events WHERE id=?',reservation.id);throw e;}}
 if(p.startsWith('/api/admin/')){admin(u);if(p==='/api/admin/analytics'){const users=await db.all('SELECT id,created FROM users');const paid=await db.all('SELECT amount,created FROM payments WHERE status=?','paid');const subs=await db.all('SELECT * FROM subscriptions WHERE expires>?',now());return send(200,{users:users.length,activeSubscriptions:subs.length,revenue:paid.reduce((a,x)=>a+x.amount,0),monthlyRevenue:paid.filter(x=>x.created.slice(0,7)===now().slice(0,7)).reduce((a,x)=>a+x.amount,0),downloads:(await list('downloads')).length,templates:(await list('templates')).length,voiceUsage:(await db.get("SELECT COUNT(*) AS n FROM usage_events WHERE kind='voice'")).n});}
 if(p==='/api/admin/audit')return send(200,await db.all('SELECT * FROM audit_logs ORDER BY created DESC LIMIT 200'));
 if(p==='/api/admin/payments')return send(200,await db.all('SELECT * FROM payments ORDER BY created DESC'));
 if(p==='/api/admin/users'&&req.method==='GET')return send(200,(await db.all('SELECT * FROM users')).map(safeUser));
 const um=p.match(/^\/api\/admin\/users\/([\w-]+)$/);if(um&&req.method==='PUT'){const {data:b}=await body(req);if(um[1]===u.id&&b.active===false)fail(400,'Cannot disable your own account.');await db.run('UPDATE users SET active=? WHERE id=?',b.active?1:0,um[1]);await audit(u.id,'user.update',um[1]);return send(200,{ok:true});}
 const sub=p.match(/^\/api\/admin\/subscriptions\/([\w-]+)$/);if(sub&&req.method==='PUT'){const {data:b}=await body(req);if(!await get('plans',b.planId)||!Number.isFinite(Date.parse(b.expires)))fail(400,'Invalid plan or expiry.');await db.run('INSERT INTO subscriptions VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET plan_id=excluded.plan_id,starts=excluded.starts,expires=excluded.expires',sub[1],b.planId,now(),new Date(b.expires).toISOString());await audit(u.id,'subscription.update',sub[1]);return send(200,{ok:true});}
 const m=p.match(/^\/api\/admin\/(templates|plans|settings|coupons|notifications)(?:\/([\w-]+))?$/);if(m){const[,kind,id]=m;if(req.method==='GET')return send(200,id?await get(kind,id):await list(kind));if(['POST','PUT'].includes(req.method)){const {data:b}=await body(req);const key=id||uid();await put(kind,key,validate(kind,b,key));await audit(u.id,kind+'.save',key);return send(200,{id:key});}if(req.method==='DELETE'&&id){if(kind==='settings'||kind==='plans')fail(400,'Disable a plan rather than delete it.');await db.run('DELETE FROM records WHERE kind=? AND id=?',kind,id);await audit(u.id,kind+'.delete',id);return send(200,{ok:true});}}
 }
 fail(404,'Endpoint not found.');
 }catch(e){if(res.headersSent){res.end();return;}send(e.status||500,{error:e.status?e.message:'Operation failed. Check server logs.'});if(!e.status)console.error(e.message);}
});
server.listen(Number(process.env.PORT||8080),process.env.HOST||'127.0.0.1',()=>console.log('DMS NEWS API ready on port '+(process.env.PORT||8080)));
