'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const offline=location.protocol==='file:'||window.DMS_OFFLINE===true;
let config=structuredClone(DMS_SEED),user=null,page='overview',editing=null,templates=[],plans=[];
if(offline){try{config=JSON.parse(localStorage.getItem('dms-control-preview'))||config}catch{}templates=config.templates;plans=config.plans;}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',5000)}
async function api(p,method='GET',data){const r=await fetch('/api'+p,{method,headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const b=await r.json();if(!r.ok)throw new Error(b.error||'Request failed');return b}
async function run(fn){try{await fn()}catch(e){toast(e.message)}}
function modal(title,body){$('#dialog').innerHTML=`<div class="dialog-head"><h2>${esc(title)}</h2><button onclick="document.querySelector('#dialog').close()">Close</button></div>${body}`;$('#dialog').showModal()}
function input(k,label,value='',type='text',extra=''){return `<label for="a-${k}">${esc(label)}</label><input id="a-${k}" name="${k}" type="${type}" value="${esc(value)}" ${extra}>`}
function area(k,label,value=''){return `<label for="a-${k}">${esc(label)}</label><textarea id="a-${k}" name="${k}">${esc(value)}</textarea>`}
function check(k,label,value){return `<label class="check"><input name="${k}" type="checkbox" ${value?'checked':''}>${esc(label)}</label>`}
function select(k,label,values,value){return `<label for="a-${k}">${esc(label)}</label><select name="${k}" id="a-${k}">${values.map(v=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(v||'None')}</option>`).join('')}</select>`}
async function load(){if(!offline){config=await api('/config');templates=await api('/admin/templates');plans=await api('/admin/plans');}}
function login(){modal('DMS CONTROL — Admin login',`<form onsubmit="event.preventDefault();signIn(this)">${input('email','Admin email','','email','required autocomplete="username"')}${input('password','Password','','password','required minlength="12" autocomplete="current-password"')}<button class="primary full">Log in</button></form><p>No default admin password. Create your account using the deployment guide.</p>`)}
async function signIn(form){await run(async()=>{const r=await api('/admin-auth/login','POST',Object.fromEntries(new FormData(form)));user=r.user;await load();$('#dialog').close();await render()})}
async function logout(){await run(async()=>{await api('/admin-auth/logout','POST',{});user=null;templates=[];plans=[];render()})}
async function go(p){page=p;await render()}
async function render(){ $('#app').innerHTML=`<div class="admin-wrap"><header class="admin-header"><div class="row"><img src="${window.DMS_LOGO||'/assets/logo.jpeg'}" alt="DMS"><div><h1>DMS CONTROL</h1><small>Catalog & subscription management</small></div></div><div class="row"><button onclick="document.body.classList.toggle('dark')">Light / dark</button>${!offline?`<button onclick="${user?'logout()':'login()'}">${user?'Log out':'Admin login'}</button>`:''}</div></header>${offline?'<div class="note">Offline admin preview. Changes stay in this preview and do not update a live app.</div>':''}${user||offline?`<nav class="tabs">${['overview','templates','plans','festivals','settings','users','payments','audit'].map(p=>`<button class="${p===page?'active':''}" onclick="go('${p}')">${p[0].toUpperCase()+p.slice(1)}</button>`).join('')}</nav><main id="content"></main>`:'<div class="panel"><h2>Secure administration</h2><p>Sign in with your administrator account to manage DMS NEWS.</p><button class="primary" onclick="login()">Log in</button></div>'}</div>`;
 if(!user&&!offline)return;await run(async()=>{const c=$('#content');if(page==='overview'){const a=offline?{users:0,downloads:0,revenue:0,activeSubscriptions:0}:await api('/admin/analytics');c.innerHTML=`<div class="stat-grid">${[['Users',a.users],['Subscriptions',a.activeSubscriptions],['Revenue','₹'+a.revenue/100],['Downloads',a.downloads]].map(([k,v])=>`<div class="stat"><small>${k}</small><strong>${esc(v)}</strong></div>`).join('')}</div><div class="panel"><h2>Publish once. Update your apps.</h2><p>Templates: ${templates.length} · Plans: ${plans.length} · Festivals: ${config.settings.festivals.length}</p><p>Users receive changes when they open or refresh DMS NEWS.</p></div>`;}
 if(['templates','plans'].includes(page)){const rows=page==='templates'?templates:plans;c.innerHTML=`<button class="primary" onclick="edit('${page}')">＋ Add ${page==='templates'?'template':'plan'}</button><div class="grid" style="margin-top:20px">${rows.map(t=>`<div class="panel">${t.background?`<img class="admin-preview" src="${esc(t.background)}" alt="Template preview">`:''}<h2>${esc(t.name)}</h2><p>${page==='plans'?'₹'+t.price/100+' / '+t.days+' days':esc(t.category)+' · '+esc(t.format)}</p><p>${t.active?'Published / active':'Disabled'} · ${t.premium?'Premium':'Free access'}</p><button data-id="${esc(t.id)}" onclick="edit('${page}',this.dataset.id)">Edit</button>${page==='templates'?` <button data-id="${esc(t.id)}" onclick="removeTemplate(this.dataset.id)">Delete</button>`:''}</div>`).join('')}</div>`;}
 if(page==='settings'||page==='festivals')editSettings(false);
 if(['users','payments','audit'].includes(page)){const rows=offline?[]:await api('/admin/'+page);c.innerHTML=`<div class="panel table-wrap"><h2>${esc(page)}</h2>${rows.length?`<table>${rows.map(r=>`<tr><td>${esc(r.name||r.action||r.plan_id)}</td><td>${esc(r.email||r.target||r.id)}</td><td>${esc(r.status||r.created)}</td>${page==='users'?`<td><button data-id="${esc(r.id)}" onclick="toggleUser(this.dataset.id,${!r.active})">${r.active?'Disable':'Activate'}</button></td>`:page==='payments'?`<td>₹${r.amount/100}</td>`:''}</tr>`).join('')}</table>`:'<p>No records.</p>'}</div>`;}
 });}
function edit(kind,id){const t=(kind==='templates'?templates:plans).find(x=>x.id===id)|| (kind==='templates'?{name:'',category:config.settings.categories[0],format:'16:9',color:'#e72c55',headline:'YOUR HEADLINE',active:false,premium:false}:{name:'',price:0,days:30,voiceLimit:100,exportLimit:100,resolution:1080,active:false,premium:true,watermark:false});editing={kind,id,original:structuredClone(t)};
 let html=input('name','Name',t.name,'text','required maxlength="120"');if(kind==='templates'){html+=`<div class="form-grid"><div>${select('category','Category',[...config.settings.categories,'Festival'],t.category)}</div><div>${select('festival','Festival',['',...config.settings.festivals],t.festival||'')}</div><div>${select('format','Format',['16:9','9:16','1:1','4:5'],t.format)}</div><div>${input('color','Accent color',t.color,'color')}</div></div>${input('headline','Default headline',t.headline)}${area('description','Description',t.description)}${input('tags','Tags (comma separated)',(t.tags||[]).join(', '))}<label for="background">Background design — JPG / PNG, maximum 4 MB</label><input id="background" type="file" name="background" accept="image/png,image/jpeg">${t.background?'<p>Existing background is kept unless replaced.</p>'+check('clearBackground','Remove current background',false):''}${input('publishAt','Publish date',t.publishAt?.slice(0,16)||'','datetime-local')}${input('expiresAt','Expiry date',t.expiresAt?.slice(0,16)||'','datetime-local')}<small>Schedule fields use UTC.</small>`;}else html+=`<div class="form-grid">${[['price','Price (₹)',t.price/100],['days','Validity (days)',t.days],['voiceLimit','AI voice limit',t.voiceLimit],['exportLimit','Export limit',t.exportLimit]].map(([k,l,v])=>`<div>${input(k,l,v,'number',`required min="${k==='days'?1:0}" step="${k==='price'?'.01':'1'}" ${id==='free'&&k==='price'?'readonly':''}`)}</div>`).join('')}</div>${select('resolution','Maximum resolution',[720,1080],t.resolution)}${check('watermark','Add DMS watermark',t.watermark)}`;
 html+=check('premium',kind==='plans'?'Premium template access':'Premium template',t.premium)+check('active','Publish / activate',t.active);modal(kind==='templates'?'Edit template':'Edit subscription plan',`<form onsubmit="event.preventDefault();save(this)">${html}<button class="primary full">Save changes</button></form>`);}
async function save(form){await run(async()=>{const f=new FormData(form),{kind,id,original}=editing;const b={...original,name:f.get('name').trim(),active:f.has('active'),premium:f.has('premium')};if(kind==='plans'){for(const k of ['days','voiceLimit','exportLimit','resolution'])b[k]=Number(f.get(k));b.price=Math.round(Number(f.get('price'))*100);b.watermark=f.has('watermark');if(id==='free'&&(b.price!==0||!b.active))throw new Error('Free plan must stay active and free.');if(id!=='free'&&b.active&&b.price<100)throw new Error('Enter a price of at least ₹1 to activate this plan.');}else{for(const k of ['category','festival','format','color','headline','description','publishAt','expiresAt'])b[k]=f.get(k)||'';for(const k of ['publishAt','expiresAt'])if(b[k])b[k]=new Date(b[k]+'Z').toISOString();b.tags=String(f.get('tags')).split(',').map(s=>s.trim()).filter(Boolean);if(f.has('clearBackground'))delete b.background;const file=f.get('background');if(file?.size){if(!['image/png','image/jpeg'].includes(file.type)||file.size>4*1024*1024)throw new Error('Choose a JPG/PNG under 4 MB.');b.background=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=()=>no(new Error('Image read failed'));r.readAsDataURL(file)});}}
 const key=id||crypto.randomUUID();if(offline){b.id=key;const rows=kind==='templates'?templates:plans;const n=rows.findIndex(x=>x.id===key);if(n<0)rows.push(b);else rows[n]=b;persist();}else{await api('/admin/'+kind+'/'+key,'PUT',b);await load();}$('#dialog').close();await render();toast('Saved. Refresh DMS NEWS to load your changes.');});}
function persist(){config.templates=templates;config.plans=plans;localStorage.setItem('dms-control-preview',JSON.stringify(config))}
function editSettings(){const s=config.settings;$('#content').innerHTML=`<div class="panel"><form onsubmit="event.preventDefault();saveSettings(this)">${page==='festivals'?area('festivals','Festivals — one per line',s.festivals.join('\n')):input('appName','App name',s.appName)+input('supportEmail','Support email',s.supportEmail,'email')+input('whatsapp','WhatsApp number',s.whatsapp)+area('categories','Categories — one per line',s.categories.join('\n'))+area('languages','Languages — one per line',s.languages.join('\n'))+area('terms','Terms',s.terms)+area('privacy','Privacy policy',s.privacy)+area('refund','Refund policy',s.refund)+check('maintenance','Maintenance mode',s.maintenance)}<button class="primary">Save settings</button></form></div>`;}
async function saveSettings(form){await run(async()=>{const f=new FormData(form),s={...config.settings};for(const[k,v]of f)s[k]=['festivals','categories','languages'].includes(k)?String(v).split('\n').map(x=>x.trim()).filter(Boolean):v;if(page==='settings')s.maintenance=f.has('maintenance');if(offline){config.settings=s;persist();}else{await api('/admin/settings/app','PUT',s);await load();}toast('Settings saved');});}
async function removeTemplate(id){if(!confirm('Delete this template from the catalog?'))return;await run(async()=>{if(offline){templates=templates.filter(x=>x.id!==id);persist();}else{await api('/admin/templates/'+id,'DELETE');await load();}render()});}
async function toggleUser(id,active){await run(async()=>{await api('/admin/users/'+id,'PUT',{active});render()});}
(async()=>{if(!offline)try{user=(await api('/admin-auth/me')).user;await load()}catch{}await render()})();
