'use strict';
const offline=location.protocol==='file:'||window.DMS_OFFLINE===true;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=o=>JSON.parse(JSON.stringify(o));
function stored(k,d){try{return JSON.parse(localStorage.getItem('dms-'+k))??d}catch{return d}}
function saveLocal(k,v){try{localStorage.setItem('dms-'+k,JSON.stringify(v))}catch{toast('Storage is full. Please remove unused local drafts and try again.')}}
let config=clone(DMS_SEED),user=null,me=null,page='home',filter='',query='',access='all',editorTab='story';
let projects=stored('projects',[]),favs=stored('favs',[]),downloads=stored('downloads',[]),picture=null,customLogo=null;
let draft={name:'Untitled news',headline:'आपकी खबर, आपकी आवाज़',subheadline:'हर खबर के साथ, हर कदम पर',breaking:'BREAKING NEWS',reporter:'',location:'',channel:'DMS NEWS',ticker:'सबसे पहले, सबसे सटीक • DMS NEWS',script:'',format:'16:9',color:'#df2349',fontSize:70,x:0.075,y:0.56,rotation:0,templateId:'news-0',language:'Hindi',gender:'Female',style:'Professional',speed:1,pitch:1,volume:1,clips:[],duration:15,clipVolume:1,musicVolume:.12,voiceVolume:1,tickerSpeed:75};
let toastTimer;
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',5000)}
async function api(path,method='GET',data){const r=await fetch('/api'+path,{method,headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const b=await r.json();if(!r.ok)throw new Error(b.error||'Request failed');return b}
async function run(fn){try{return await fn()}catch(e){toast(e.message)}}
function modal(title,html){$('#dialog').innerHTML=`<div class="dialog-head"><h2>${esc(title)}</h2><button class="quiet" onclick="document.querySelector('#dialog').close()">✕</button></div>${html}`;$('#dialog').showModal()}
const nav=[['home','◫','Dashboard'],['templates','▦','News templates'],['festivals','✧','Festival studio'],['editor','＋','Create news'],['voice','♫','Voice studio'],['projects','▤','My projects'],['favourites','♡','Favourites'],['downloads','↓','My downloads'],['subscription','♔','My subscription'],['profile','◉','Profile'],['help','?','Help & support']];
function go(p){if(!nav.some(x=>x[0]===p))return;if(p!==page&&['templates','festivals','favourites'].includes(p)){filter='';query='';access='all';}page=p;render()}
function render(){document.querySelector('#splash .logo3d').innerHTML='<img alt="DMS" src="'+(window.DMS_LOGO||'/assets/logo.jpeg')+'" style="width:140px;border-radius:20px">';document.body.classList.toggle('dark',stored('dark',false));$('#app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><img src="${window.DMS_LOGO||'/assets/logo.jpeg'}" alt="DMS logo"><div><b>DMS NEWS</b><small>CREATOR STUDIO</small></div></div><div class="nav-label">YOUR WORKSPACE</div><nav class="nav">${nav.map(([id,icon,label],i)=>`${i===8?'<div class="nav-label">YOUR ACCOUNT</div>':''}<button class="${page===id?'active':''}" onclick="go('${id}')"><span>${icon}</span>${label}</button>`).join('')}</nav><div class="sidebar-foot"><div class="mini"><b style="color:white">Your story deserves a voice.</b><p style="margin:7px 0 0">Create with DMS.<br>Made for every storyteller.</p></div></div></aside><div class="workspace"><header class="topbar"><div class="row"><button class="mobile-menu quiet" onclick="document.querySelector('.sidebar').classList.toggle('open')">☰</button><span class="wordmark">DMS / ${esc(nav.find(x=>x[0]===page)?.[2]||'Studio')}</span></div><div class="right"><span class="badge">${offline?'OFFLINE PREVIEW':user?'CONNECTED':'PREVIEW'}</span><button class="small" onclick="refreshCatalog()">Refresh</button><button class="quiet" aria-label="Toggle theme" onclick="saveLocal('dark',!stored('dark',false));render()">◐</button><button class="small" onclick="${user?'logout()':'login()'}">${user?'Log out':'Log in'}</button><div class="avatar">${esc(user?.name?.[0]||'D')}</div></div></header><main class="main" id="main"></main></div></div>`;const views={home,templates:()=>library(false),festivals:()=>library(true),favourites:()=>library(false,true),editor,voice,projects:projectPage,downloads:downloadPage,subscription,profile,help};views[page]();}
function heading(eyebrow,title,description,action=''){return `<div class="section-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p class="muted" style="margin:8px 0 0">${description}</p></div>${action}</div>`}
function home(){$('#main').innerHTML=heading('THE CREATOR WORKSPACE',`Let’s make headlines.`,`Turn your story into news worth sharing.`,`<button class="primary" onclick="go('editor')">＋ Create news</button>`)+`<section class="hero"><div class="hero-copy"><div class="eyebrow">ONE STORY. ENDLESS POSSIBILITIES.</div><h2>From a headline<br>to your next big story.</h2><p>News graphics, festival greetings and social posts. All in your own voice, all in one studio.</p><button class="primary" onclick="go('templates')">Explore templates &nbsp; →</button></div><div class="hero-art"><div class="mini-screen"><div class="screen-top"><span>DMS NEWS</span><span>● LIVE</span></div><div class="screen-body">YOUR VOICE.</div><div class="screen-bottom">BREAKING &nbsp; | &nbsp; YOUR STORY STARTS HERE</div></div></div></section><div class="stat-grid">${stat('Saved projects',projects.length,'▤')+stat('Original templates',config.templates.length,'▦')+stat('Festival occasions',config.settings.festivals.length,'✧')+stat('Your downloads',downloads.length,'↓')}</div><div class="row between"><h2>What will you create today?</h2><small>Start with your story</small></div><div class="services">${[['ϟ','Breaking News'],['▶','News Video'],['▣','News Poster'],['▧','News Thumbnail'],['▱','Reporter Frame'],['✧','Festival Greetings']].map(([i,s])=>`<button class="service" onclick="service('${s}')"><i>${i}</i>${s}</button>`).join('')}</div><div class="row between"><h2>Made for your next headline</h2><button class="quiet small" onclick="go('templates')">View all templates →</button></div><div class="grid">${config.templates.slice(0,3).map(card).join('')}</div><div class="footer">DMS NEWS · Powered by DMS Digital Media Service · ${offline?'Local preview — your drafts stay in this browser.':'Connected workspace'}</div>`}
function stat(label,value,icon){return `<div class="stat"><em>${icon}</em><small>${label}</small><strong>${value}</strong></div>`}
function service(s){if(s==='Festival Greetings')return go('festivals');const t=config.templates.find(t=>t.name===s);choose(t?.id||'news-0')}
function card(t){return `<article class="template"><div class="thumb" style="--tcolor:${/^#[0-9a-f]{6}$/i.test(t.color)?t.color:'#e32c49'}"><div class="row between"><span class="tag">DMS NEWS / ${esc(t.format)}</span><span class="badge">${t.premium?'PREMIUM':'FREE'}</span></div><div class="sample">${esc(t.festival?'Happy\n'+t.festival:t.name.toUpperCase())}</div><div class="line"></div></div><div class="template-body"><h3>${esc(t.name)}</h3><small>${esc(t.description||t.category)} · ${esc(t.format)}</small><div class="row"><button class="primary small" data-template="${esc(t.id)}" onclick="choose(this.dataset.template)">Use template →</button><button class="star" data-template="${esc(t.id)}" aria-label="Favourite ${esc(t.name)}" onclick="favourite(this.dataset.template)">${favs.includes(t.id)?'♥':'♡'}</button></div></div></article>`}
function library(festival,favourites=false){const cats=festival?config.settings.festivals:config.settings.categories;$('#main').innerHTML=heading(festival?'CELEBRATE EVERY OCCASION':favourites?'YOUR COLLECTION':'THE TEMPLATE LIBRARY',festival?'Every festival. Your style.':favourites?'Saved inspiration.':'A fresh look for every story.',festival?'Original greeting layouts, ready for your name and channel.':'Choose a design. Make it your own.')+`<div class="filters"><input placeholder="Search templates…" value="${esc(query)}" oninput="query=this.value;filterCards(${festival},${favourites})"><select onchange="filter=this.value;filterCards(${festival},${favourites})"><option value="">All ${festival?'festivals':'categories'}</option>${cats.map(c=>`<option ${c===filter?'selected':''}>${esc(c)}</option>`).join('')}</select><select onchange="access=this.value;filterCards(${festival},${favourites})"><option value="all">All access</option><option value="free" ${access==='free'?'selected':''}>Free</option><option value="premium" ${access==='premium'?'selected':''}>Premium</option></select></div><div class="grid" id="cards"></div>`;filterCards(festival,favourites)}
function filterCards(festival,favourites){const a=config.templates.filter(t=>(favourites?favs.includes(t.id):festival?!!t.festival:!t.festival)&&(!filter||(festival?t.festival===filter:t.category===filter))&&(!query||(t.name+' '+t.category).toLowerCase().includes(query.toLowerCase()))&&(access==='all'||(access==='premium')===!!t.premium));$('#cards').innerHTML=a.length?a.map(card).join(''):'<div class="empty"><h2>No templates found</h2>Try another category or search.</div>'}
async function favourite(id){if(favs.includes(id)){favs=favs.filter(x=>x!==id);if(user&&!offline){const rows=await api('/favourites');for(const r of rows.filter(x=>x.templateId===id))await api('/favourites/'+r.id,'DELETE')}}else{favs.push(id);if(user&&!offline)await api('/favourites','POST',{templateId:id})}saveLocal('favs',favs);render()}
function choose(id){const t=config.templates.find(t=>t.id===id);if(!t)return;draft={...draft,id:undefined,name:t.name,headline:t.headline||(t.festival?'Happy '+t.festival:'आपकी खबर, आपकी आवाज़'),format:t.format,color:t.color,templateId:id};picture=null;draft.image=t.background||null;page='editor';render();restoreImages();if(t.premium)toast(offline?'Premium layout preview. Online export requires an eligible plan.':'Premium template selected. Export checks your plan.')}
function field(key,label,type='text'){return `<label for="f-${key}">${label}</label><input id="f-${key}" type="${type}" value="${esc(draft[key]||'')}" oninput="draft['${key}']=this.value;draw()">`}
function editor(){$('#main').innerHTML=heading('YOUR STORY, IN FOCUS','News creator','Choose your words. Shape your frame.',`<button class="primary" onclick="saveProject()">Save draft</button>`)+`<div class="editor"><div class="panel"><div class="tabs">${['story','design','media','timeline','voice'].map(t=>`<button class="small ${editorTab===t?'active':''}" onclick="editorTab='${t}';editor()">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div><div id="editor-fields"></div></div><div class="editor-preview"><div class="row between" style="margin-bottom:12px"><b>Live preview</b><small>Drag the headline to position it</small></div><div class="canvas-wrap"><canvas id="canvas" width="1280" height="720"></canvas></div><div class="row" style="margin-top:16px"><button class="primary" onclick="exportDesign('png')">↓ PNG</button><button onclick="exportDesign('jpg')">↓ JPG</button><button onclick="exportDesign('mp4')">↓ MP4</button><button onclick="sameDesign()">Same design</button></div><p class="muted" style="font-size:11px;margin-top:12px">PNG/JPG: ${offline?'local graphic export':'server-rendered export'}. MP4: connected timeline export with clips, narration, music and intro/outro. Maximum total length: 180 seconds.</p></div></div>`;editorFields();draw();const c=$('#canvas');let dragging=false;c.onpointerdown=e=>{dragging=true;c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!dragging)return;const r=c.getBoundingClientRect();draft.x=Math.max(.01,Math.min(.8,(e.clientX-r.left)/r.width));draft.y=Math.max(.12,Math.min(.82,(e.clientY-r.top)/r.height));draw()};c.onpointerup=()=>dragging=false}
function editorFields(){let html='';if(editorTab==='story')html=field('name','Project name')+field('headline','Main headline')+field('subheadline','Sub headline')+field('breaking','Breaking bar')+`<div class="two">${field('reporter','Reporter name')+field('location','Location')}</div>`+field('channel','Channel name')+field('ticker','News ticker')+`<label>News script</label><textarea oninput="draft.script=this.value">${esc(draft.script)}</textarea>`;
 if(editorTab==='design')html=`<label>Canvas format</label><select onchange="draft.format=this.value;draw()">${['16:9','9:16','1:1','4:5'].map(x=>`<option ${draft.format===x?'selected':''}>${x}</option>`).join('')}</select>`+field('color','Accent color','color')+`<label>Headline size · ${draft.fontSize}px</label><input type="range" min="28" max="120" value="${draft.fontSize}" oninput="draft.fontSize=+this.value;draw()"><label>Headline rotation</label><input type="range" min="-30" max="30" value="${draft.rotation}" oninput="draft.rotation=+this.value;draw()"><div class="row" style="margin-top:20px"><button onclick="draft.x=.075;draft.y=.56;draft.rotation=0;draw()">Reset position</button><button onclick="draft.headline='';draw()">Clear headline</button></div><div class="note">Drag the headline directly on the preview. Image crop uses center-fill. Full multi-layer editing is pending.</div>`;
 if(editorTab==='media')html=`<label>Background image · JPG / PNG</label><input type="file" accept="image/png,image/jpeg" onchange="uploadImage(this.files[0],false)"><label>Channel logo · JPG / PNG</label><input type="file" accept="image/png,image/jpeg" onchange="uploadImage(this.files[0],true)"><label>Add a video clip</label><input type="file" accept="video/mp4,video/webm" onchange="uploadTrack(this.files[0],'clip')"><video id="media-video" controls class="asset-video" style="margin-top:15px" hidden></video><div class="note">Connected uploads are saved privately. Use Timeline to trim and reorder clips, add audio and export MP4. In offline preview, a selected clip can only be played locally.</div><button onclick="picture=null;draft.image=null;draw()">Remove image</button>`;
 if(editorTab==='timeline')html=timelineFields();
 if(editorTab==='voice')html=voiceFields();$('#editor-fields').innerHTML=html;}
function draw(transparent=false,skipTicker=false){const c=$('#canvas');if(!c)return;const sizes={'16:9':[1280,720],'9:16':[720,1280],'1:1':[1080,1080],'4:5':[864,1080]};[c.width,c.height]=sizes[draft.format]||sizes['16:9'];const x=c.getContext('2d'),w=c.width,h=c.height;
 if(!transparent){let g=x.createLinearGradient(0,0,w,h);g.addColorStop(0,'#101b30');g.addColorStop(1,draft.color||'#d62549');x.fillStyle=g;x.fillRect(0,0,w,h);
 if(picture){const scale=Math.max(w/picture.width,h/picture.height);x.drawImage(picture,(w-picture.width*scale)/2,(h-picture.height*scale)/2,picture.width*scale,picture.height*scale);g=x.createLinearGradient(0,h*.2,0,h);g.addColorStop(0,'#00000000');g.addColorStop(1,'#000000e8');x.fillStyle=g;x.fillRect(0,0,w,h)}else{for(let r=100;r<600;r+=80){x.beginPath();x.arc(w*.77,h*.35,r,0,Math.PI*2);x.strokeStyle='#ffffff12';x.lineWidth=2;x.stroke()}}
 }else{x.clearRect(0,0,w,h);const shade=x.createLinearGradient(0,h*.38,0,h*.88);shade.addColorStop(0,'#00000000');shade.addColorStop(1,'#000000bb');x.fillStyle=shade;x.fillRect(0,h*.38,w,h*.50);}
 x.fillStyle='#ffffff';x.fillRect(0,0,w,h*.09);x.fillStyle='#162137';x.font=`bold ${Math.round(w*.024)}px Arial`;x.fillText(draft.channel||'DMS NEWS',w*.045,h*.057);x.fillStyle=draft.color;x.fillText('● LIVE',w*.84,h*.057);
 if(customLogo)x.drawImage(customLogo,w*.80,h*.12,w*.13,w*.13*customLogo.height/customLogo.width);
 x.fillStyle=draft.color;x.fillRect(w*.06,h*.38,Math.min(w*.61,600),h*.065);x.fillStyle='white';x.font=`bold ${Math.round(w*.028)}px Arial`;x.fillText((draft.breaking||'NEWS').slice(0,35),w*.08,h*.423);
 x.save();x.translate(w*draft.x,h*draft.y);x.rotate(draft.rotation*Math.PI/180);x.font=`bold ${draft.fontSize}px Arial`;x.fillStyle='white';wrapText(x,draft.headline,0,0,w*.85,draft.fontSize*1.18,4);x.restore();x.font=`${Math.round(w*.023)}px Arial`;x.fillStyle='#e3e7f0';wrapText(x,draft.subheadline,w*.075,h*.79,w*.83,w*.03,2);
 x.fillStyle='#101a2e';x.fillRect(0,h*.865,w,h*.065);x.fillStyle='white';x.font=`bold ${Math.round(w*.021)}px Arial`;x.fillText([draft.reporter,draft.location].filter(Boolean).join('  |  '),w*.06,h*.909);
 x.fillStyle=draft.color;x.fillRect(0,h*.93,w,h*.07);x.fillStyle='white';x.font=`${Math.round(w*.019)}px Arial`;if(!skipTicker)x.fillText(draft.ticker||'',w*.04,h*.973);
 if(offline||!me?.plan||me.plan.watermark){x.fillStyle='#ffffffaa';x.font=`${Math.max(12,Math.round(w*.013))}px Arial`;x.fillText('Created with DMS NEWS',w*.70,h*.847)}
}
function wrapText(ctx,text,x,y,max,line,maxLines){const words=String(text||'').split(/\s+/);let current='',row=0;for(const word of words){if(ctx.measureText(current+' '+word).width>max&&current){ctx.fillText(current,x,y+row*line);current=word;if(++row>=maxLines)return}else current+=(current?' ':'')+word;}ctx.fillText(current,x,y+row*line)}
function uploadImage(file,logo){if(!file)return;if(!['image/png','image/jpeg'].includes(file.type)||file.size>4*1024*1024)return toast('Choose a JPG/PNG under 4 MB.');const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{if(logo){customLogo=img;draft.logo=reader.result}else{picture=img;draft.image=reader.result}draw()};img.src=reader.result};reader.readAsDataURL(file)}
let videoURL;function previewVideo(f){if(!f)return;if(videoURL)URL.revokeObjectURL(videoURL);videoURL=URL.createObjectURL(f);$('#media-video').src=videoURL;$('#media-video').hidden=false;}
const langCodes={Hindi:'hi-IN',English:'en-IN',Hinglish:'hi-IN',Gujarati:'gu-IN',Marathi:'mr-IN',Punjabi:'pa-IN',Bengali:'bn-IN',Tamil:'ta-IN',Telugu:'te-IN',Malayalam:'ml-IN',Kannada:'kn-IN',Urdu:'ur-IN'};
function voiceFields(){return `<label>Script</label><textarea oninput="draft.script=this.value">${esc(draft.script)}</textarea><div class="two"><div><label>Language</label><select onchange="draft.language=this.value">${config.settings.languages.map(x=>`<option ${x===draft.language?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div><label>Voice gender</label><select onchange="draft.gender=this.value">${['Female','Male'].map(x=>`<option ${x===draft.gender?'selected':''}>${x}</option>`).join('')}</select></div></div><label>Voice style</label><select onchange="draft.style=this.value">${['Soft','Hard','Serious','Professional','Breaking News','Energetic','Calm','Emotional','Tense','Reporter','Anchor'].map(x=>`<option ${x===draft.style?'selected':''}>${x}</option>`).join('')}</select>${['speed','pitch','volume'].map(k=>`<label>${k[0].toUpperCase()+k.slice(1)}</label><input type="range" min="${k==='volume'?0:.5}" max="${k==='volume'?1:2}" step=".1" value="${draft[k]}" oninput="draft.${k}=+this.value">`).join('')}<div class="row" style="margin-top:20px"><button class="primary" onclick="generateVoice()">Generate AI voice</button><button onclick="browserVoice()">Device preview</button><button onclick="window.speechSynthesis?.cancel()">Stop</button></div><div class="note">Device preview uses installed browser voices. Gender/style availability depends on the device; it does not create an exportable AI audio file.</div><audio id="ai-audio" controls hidden></audio>`}
function voice(){$('#main').innerHTML=heading('VOICE STUDIO','Let your story be heard.','Write in your language. Choose the tone of your story.')+`<div class="editor"><div class="panel">${voiceFields()}</div><div class="panel"><h2>Script assistant</h2><p class="muted">Generate editable copy from the facts you provide.</p><label>Main facts / topic</label><textarea id="ai-facts" placeholder="What happened, where, when and verified details"></textarea><label>Length</label><select id="ai-duration">${['15 Seconds','30 Seconds','45 Seconds','60 Seconds','2 Minutes','Long News'].map(x=>`<option>${x}</option>`).join('')}</select><button style="margin-top:18px" class="primary" onclick="generateScript()">Generate script</button><p class="muted" style="margin-top:15px">${config.capabilities?.ai?'AI adapter connected. Review generated facts before publishing.':'AI provider is not connected. You can still write and preview your own script.'}</p></div></div>`}
function browserVoice(){if(!draft.script.trim())return toast('Please enter a script first.');if(!window.speechSynthesis)return toast('Device speech is not available in this browser.');const voices=speechSynthesis.getVoices(),lang=langCodes[draft.language],v=voices.find(v=>v.lang.toLowerCase().startsWith(lang?.split('-')[0]||'en'));if(!v)return toast('No '+draft.language+' voice is installed on this device.');speechSynthesis.cancel();const s=new SpeechSynthesisUtterance(draft.script);s.voice=v;s.lang=lang;s.rate=draft.speed;s.pitch=draft.pitch;s.volume=draft.volume;speechSynthesis.speak(s)}
function requireLogin(){if(offline){toast('This action needs the connected backend. See the source package guide.');return false}if(!user){login();return false}return true}
async function generateVoice(){if(!requireLogin())return;await run(async()=>{const r=await api('/ai/voice','POST',{script:draft.script,language:draft.language,gender:draft.gender,style:draft.style,speed:draft.speed,pitch:draft.pitch,volume:draft.volume});if(!r.audioUrl||!(/^https:\/\//.test(r.audioUrl)||/^\/api\/media\/[a-f0-9-]{36}$/.test(r.audioUrl)))throw new Error('Provider did not return a valid HTTPS audio URL.');$('#ai-audio').src=r.audioUrl;$('#ai-audio').hidden=false;if(r.mediaId){draft.narrationId=r.mediaId;draft.narrationName='Generated AI voice';draft.voiceVolume=1;}toast(r.mediaId?'Voice generated and applied to the video timeline.':'Voice generated. Preview below.');})}
async function generateScript(){if(!requireLogin())return;const facts=$('#ai-facts').value,duration=$('#ai-duration').value;await run(async()=>{const r=await api('/ai/script','POST',{facts,duration,language:draft.language});draft.script=r.script||'';if(r.headline)draft.headline=r.headline;voice();toast('Generated text is ready to edit. Review it before use.')})}
async function saveProject(){await run(async()=>{const p={...clone(draft),updated:new Date().toISOString()};if(!offline){if(!requireLogin())return;const r=await api('/projects'+(p.id?'/'+p.id:''),p.id?'PUT':'POST',p);p.id=r.id;}else p.id=p.id||crypto.randomUUID();draft.id=p.id;projects=projects.filter(x=>x.id!==p.id);projects.unshift(p);offline&&saveLocal('projects',projects);toast('Draft saved. Find it in My projects.')})}
function sameDesign(){draft={...clone(draft),id:undefined,name:draft.name+' — copy'};toast('Same design copied. Update the headline and save a new draft.');editor()}
function downloadBlob(blob,name){if(window.DmsDownload){if(blob.size>64*1024*1024)return toast('This download exceeds the app’s 64 MB limit.');const reader=new FileReader();reader.onload=()=>window.DmsDownload.postMessage(JSON.stringify({name,data:reader.result}));reader.readAsDataURL(blob);return;}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000)}
async function exportDesign(format){if(mediaPending||exportBusy)return toast('Please wait for the current upload or export.');await run(async()=>{const c=$('#canvas');if(!c)return;if(offline){if(format==='mp4')return toast('MP4 rendering needs the backend and FFmpeg. PNG/JPG export works here.');downloadBlob(await new Promise(r=>c.toBlob(r,format==='jpg'?'image/jpeg':'image/png')),'DMS-news.'+format);downloads.unshift({id:crypto.randomUUID(),name:draft.name,format,created:new Date().toISOString()});saveLocal('downloads',downloads);toast('Graphic downloaded.');return;}if(!requireLogin())return;exportBusy=true;toast('Rendering your export…');try{const isVideo=format==='mp4';draw(isVideo&&!!draft.clips?.length,isVideo);const request={image:c.toDataURL('image/png'),format,name:draft.name,templateId:draft.templateId,duration:draft.duration||15};if(isVideo)Object.assign(request,{timeline:true,clips:draft.clips||[],introId:draft.introId,outroId:draft.outroId,introDuration:draft.introDuration||5,outroDuration:draft.outroDuration||5,narrationId:draft.narrationId,musicId:draft.musicId,clipVolume:draft.clipVolume??1,musicVolume:draft.musicVolume??.12,voiceVolume:draft.voiceVolume??1,voiceSpeed:draft.playbackSpeed||1,tickerImage:makeTickerImage(),tickerSpeed:draft.tickerSpeed||75});draw();const r=await api('/exports','POST',request);const response=await fetch(r.url);if(!response.ok)throw new Error('Download failed');downloadBlob(await response.blob(),'DMS-news.'+format);downloads=await api('/downloads');toast('Export is ready.');}finally{exportBusy=false;draw();}})}
function projectPage(){$('#main').innerHTML=heading('PICK UP WHERE YOU LEFT OFF','Your projects.','Saved drafts and reusable designs.',`<button class="primary" onclick="go('editor')">＋ New project</button>`)+`<div class="grid" style="margin-top:20px">${projects.length?projects.map(p=>`<div class="panel"><span class="badge">${esc(p.format)}</span><h2 style="margin-top:15px">${esc(p.name)}</h2><p class="muted">${esc(p.headline)}</p><div class="row"><button class="primary small" data-id="${esc(p.id)}" onclick="openProject(this.dataset.id)">Edit</button><button class="small" data-id="${esc(p.id)}" onclick="openProject(this.dataset.id,true)">Same design</button><button class="small" data-id="${esc(p.id)}" onclick="deleteProject(this.dataset.id)">Delete</button></div></div>`).join(''):'<div class="empty"><h2>Your next story starts here.</h2>Create a design and save your first draft.</div>'}</div>`}
function restoreImages(){picture=null;customLogo=null;for(const [key,isLogo]of [['image',false],['logo',true]])if(draft[key]&&/^data:image\/(png|jpeg);base64,/.test(draft[key])){const i=new Image();i.onload=()=>{if(isLogo)customLogo=i;else picture=i;draw()};i.src=draft[key]}}
function openProject(id,copy=false){const p=projects.find(x=>x.id===id);if(!p)return;draft=clone(p);if(copy){delete draft.id;draft.name+=' — copy'}go('editor');restoreImages()}
async function deleteProject(id){if(!confirm('Delete this project?'))return;await run(async()=>{if(!offline&&user)await api('/projects/'+id,'DELETE');projects=projects.filter(x=>x.id!==id);offline&&saveLocal('projects',projects);projectPage()})}
function downloadPage(){$('#main').innerHTML=heading('READY TO SHARE','My downloads.','Your completed graphics and videos.')+`<div class="panel table-wrap"><table><thead><tr><th>PROJECT</th><th>FORMAT</th><th>CREATED</th><th>FILE</th></tr></thead><tbody>${downloads.map(d=>`<tr><td>${esc(d.name)}</td><td>${esc(d.format.toUpperCase())}</td><td>${esc(new Date(d.created).toLocaleString())}</td><td>${d.url?`<button class="small" data-url="${esc(d.url)}" data-format="${esc(d.format)}" onclick="downloadExisting(this.dataset.url,this.dataset.format)">Download ↓</button>`:'Saved to your device'}</td></tr>`).join('')}</tbody></table>${downloads.length?'':'<div class="empty">Your exports will appear here.</div>'}</div>`}
function subscription(){$('#main').innerHTML=heading('MORE ROOM TO CREATE','Choose your creative freedom.','Plan names, prices and limits are controlled by the administrator.')+`<div class="plans">${config.plans.map(p=>`<div class="plan"><span class="badge">${esc(p.name)}</span><div class="price">${p.id==='free'?'₹0':p.active?'₹'+(p.price/100).toLocaleString('en-IN'):'Not priced'}</div><small>${p.days} days</small><ul><li>${p.exportLimit} exports</li><li>${p.voiceLimit} AI voice generations</li><li>${p.resolution}p output</li><li>${p.premium?'Premium templates':'Free templates'}</li><li>${p.watermark?'DMS watermark':'Watermark-free'}</li></ul><button class="${p.id==='monthly'?'primary':''}" ${p.id==='free'||!p.active?'disabled':''} data-id="${esc(p.id)}" onclick="checkout(this.dataset.id)">${p.id==='free'?'Free workspace':p.active?'Choose plan':'Pricing pending'}</button></div>`).join('')}</div><div class="note">Paid plans are disabled until the owner sets pricing. Offline preview cannot activate subscriptions or collect payments.</div><button onclick="paymentHistory()">Payment history</button>`}
async function checkout(id){if(new URLSearchParams(location.search||'').get('distribution')==='play')return toast('Purchases are not enabled in this Play build.');if(!requireLogin())return;await run(async()=>{const order=await api('/payments/order','POST',{planId:id});if(!window.Razorpay){await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=ok;s.onerror=()=>no(new Error('Checkout could not load'));document.head.appendChild(s)})}new Razorpay({key:order.keyId,amount:order.amount,currency:order.currency,order_id:order.orderId,name:'DMS NEWS',handler:async r=>run(async()=>{await api('/payments/verify','POST',r);me=await api('/me');toast('Payment verified. Subscription activated.');})}).open()})}
async function paymentHistory(){if(!requireLogin())return;await run(async()=>{const p=await api('/payments');modal('Payment history',p.length?`<div class="table-wrap"><table>${p.map(x=>`<tr><td>${esc(x.plan_id)}</td><td>₹${x.amount/100}</td><td>${esc(x.status)}</td><td>${esc(x.id)}</td></tr>`).join('')}</table></div>`:'<p>No payments yet.</p>')})}
function login(register=false){modal(register?'Create your DMS account':'Welcome back.',offline?'<p>This is an offline preview. Open the project through its backend to create an account or log in.</p>':`<form onsubmit="event.preventDefault();authenticate(${register})">${register?'<label>Name</label><input name="name" id="login-name" required>':''}<label>Email</label><input id="login-email" type="email" required autocomplete="email"><label>Password</label><input id="login-password" type="password" minlength="12" required autocomplete="${register?'new-password':'current-password'}"><small>Minimum 12 characters</small><button class="primary full" style="margin-top:20px">${register?'Create account':'Log in'}</button></form><button class="quiet full" onclick="login(${!register})">${register?'Already have an account? Log in':'New here? Create an account'}</button><button class="quiet full" onclick="otpLogin()">Mobile OTP login</button><small>Password recovery is not connected in this build.</small>`)}
async function authenticate(register){await run(async()=>{const r=await api('/auth/'+(register?'register':'login'),'POST',{email:$('#login-email').value,password:$('#login-password').value,name:$('#login-name')?.value});user=r.user;me=await api('/me');await sync();$('#dialog').close();render();toast('Welcome, '+user.name)})}
async function sync(){if(user&&!offline){projects=await api('/projects');downloads=await api('/downloads');favs=(await api('/favourites')).map(x=>x.templateId)}}
async function logout(){await run(async()=>{await api('/auth/logout','POST',{});user=null;me=null;projects=[];downloads=[];favs=[];go('home')})}
function profile(){$('#main').innerHTML=heading('YOUR ACCOUNT','Profile & preferences.','Your identity in the DMS ecosystem.')+`<div class="panel" style="max-width:650px">${user?`<h2>${esc(user.name)}</h2><p>${esc(user.email||user.mobile||'')}</p><span class="badge">${esc(me?.plan.name||'Free')}</span><p style="margin-top:15px">Subscription expiry: ${esc(me?.subscription?.expires||'No paid subscription')}</p><button onclick="changePassword()">Change password</button>`:`<p>${offline?'Offline preview — no account data is being sent.':'Log in to view your account.'}</p><button class="primary" onclick="login()">Log in</button>`}<hr style="border:0;border-top:1px solid var(--line);margin:25px 0"><button onclick="saveLocal('dark',!stored('dark',false));render()">Switch light / dark theme</button></div>`}
function changePassword(){modal('Change password','<label>Current password</label><input type="password" id="old-pass"><label>New password (12+ characters)</label><input type="password" id="new-pass"><button class="primary" style="margin-top:15px" onclick="run(async()=>{await api(\'/auth/password\',\'POST\',{current:document.querySelector(\'#old-pass\').value,password:document.querySelector(\'#new-pass\').value});document.querySelector(\'#dialog\').close();user=null;me=null;render();toast(\'Password changed. Please log in again.\')})">Update password</button>')}
function help(){$('#main').innerHTML=heading('WE’RE HERE TO HELP','Support & information.','A clear path from your first draft to your first export.')+`<div class="grid"><div class="panel"><h2>Quick start</h2><p>1. Choose a template.<br>2. Add your headline and image.<br>3. Save a draft.<br>4. Export your graphic.</p><p>Use “Same design” to reuse a layout.</p></div><div class="panel"><h2>Contact DMS</h2><p>${esc(config.settings.supportEmail||'Support email has not been set.')}</p><p>${esc(config.settings.whatsapp||'WhatsApp support has not been set.')}</p><button onclick="supportForm()">Report a problem</button></div><div class="panel"><h2>Policies</h2>${['terms','privacy','refund'].map(k=>`<p><button class="quiet" onclick="policy('${k}')">${k[0].toUpperCase()+k.slice(1)} policy →</button></p>`).join('')}</div></div><div class="note">This development build supports graphic editing and video composition with trimmed clips, narration, music and intro/outro. OTP, cloud AI activation, transitions, subtitles and full multi-layer editing remain pending.</div>`}
function policy(k){modal(k[0].toUpperCase()+k.slice(1)+' policy',`<p>${esc(config.settings[k]||'The platform owner has not published this policy yet.')}</p>`)}
function supportForm(){if(!requireLogin())return;modal('Report a problem','<label>Describe the issue</label><textarea id="support-text"></textarea><button class="primary" onclick="run(async()=>{await api(\'/support\',\'POST\',{message:document.querySelector(\'#support-text\').value});document.querySelector(\'#dialog\').close();toast(\'Support request saved.\')})">Submit request</button>')}
(async()=>{if(offline){config=stored('config',clone(DMS_SEED));}else{try{config=await api('/config');try{me=await api('/me');user=me.user;await sync()}catch{projects=[];favs=[];downloads=[]}}catch(e){toast('Backend unavailable: '+e.message)}}render();})();

let mediaPending=0,exportBusy=false;
function timelineFields(){return `<div class="row between"><h3>Video timeline</h3><button class="small" onclick="manageMedia()">My media</button></div><p class="muted">Up to 8 main clips. Trim and arrange them in playback order.</p><label>Add clip · MP4 / WebM, up to 64 MB</label><input type="file" accept="video/mp4,video/webm" onchange="uploadTrack(this.files[0],'clip')"><div class="timeline-list">${(draft.clips||[]).map((c,i)=>`<div class="panel" style="margin:12px 0;padding:12px"><b>${i+1}. ${esc(c.name)}</b><div class="two"><div><label>Start (seconds)</label><input type="number" min="0" max="${c.sourceDuration}" step=".1" value="${c.start}" onchange="trimClip(${i},'start',this.value)"></div><div><label>Length (seconds)</label><input type="number" min=".1" max="${c.sourceDuration-c.start}" step=".1" value="${c.duration}" onchange="trimClip(${i},'duration',this.value)"></div></div><div class="row" style="margin-top:10px"><button class="small" onclick="moveClip(${i},-1)" ${i===0?'disabled':''}>↑</button><button class="small" onclick="moveClip(${i},1)" ${i===(draft.clips||[]).length-1?'disabled':''}>↓</button><button class="small" onclick="draft.clips.splice(${i},1);editorFields()">Remove from timeline</button></div></div>`).join('')||'<p class="muted">No video clips yet. Export will use the current graphic.</p>'}</div><label>Graphic-only duration (seconds)</label><input type="number" min="1" max="180" value="${draft.duration||15}" oninput="draft.duration=+this.value"><hr style="border:0;border-top:1px solid var(--line);margin:20px 0">${[['narration','Narration / voice recording','audio/mpeg,audio/wav,audio/mp4,audio/ogg'],['music','Background music','audio/mpeg,audio/wav,audio/mp4,audio/ogg'],['intro','Intro video','video/mp4,video/webm'],['outro','Outro video','video/mp4,video/webm']].map(([k,title,types])=>`<label>${title}</label><input type="file" accept="${types}" onchange="uploadTrack(this.files[0],'${k}')"><div class="row"><small>${esc(draft[k+'Name']||'None selected')}</small>${draft[k+'Id']?`<button class="small quiet" onclick="delete draft['${k}Id'];delete draft['${k}Name'];editorFields()">Remove</button>`:''}</div>${['intro','outro'].includes(k)?`<label>${title} length (seconds)</label><input type="number" min=".1" max="20" step=".1" value="${draft[k+'Duration']||5}" oninput="draft['${k}Duration']=+this.value">`:''}`).join('')}${[['clipVolume','Original clip volume',1],['voiceVolume','Narration volume',1],['musicVolume','Music volume',.12]].map(([k,label,value])=>`<label>${label}</label><input type="range" min="0" max="1" step=".05" value="${draft[k]??value}" oninput="draft['${k}']=+this.value">`).join('')}<label>Ticker speed</label><input type="range" min="20" max="300" value="${draft.tickerSpeed||75}" oninput="draft.tickerSpeed=+this.value"><div class="note">Video/audio export needs the connected backend. Uploaded files stay private to your account. Intro/outro retain their video; the news frame appears over the main clips.</div>`;}
function trimClip(index,key,value){const clip=draft.clips[index],v=Number(value);if(!Number.isFinite(v))return;clip[key]=v;clip.start=Math.min(Math.max(0,clip.start),clip.sourceDuration-.1);clip.duration=Math.max(.1,Math.min(clip.duration,clip.sourceDuration-clip.start));editorFields();}
function moveClip(index,direction){const next=index+direction;if(next<0||next>=draft.clips.length)return;[draft.clips[index],draft.clips[next]]=[draft.clips[next],draft.clips[index]];editorFields();}
async function uploadTrack(file,kind){if(!file)return;if(kind==='clip'&&editorTab==='media')previewVideo(file);if(!requireLogin())return;if(file.size>64*1024*1024)return toast('Maximum upload size is 64 MB.');if(kind==='clip'&&(draft.clips||[]).length>=8)return toast('Maximum 8 main clips.');mediaPending++;await run(async()=>{toast('Uploading '+file.name+'…');const response=await fetch('/api/media?name='+encodeURIComponent(file.name),{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream'},body:file});const item=await response.json();if(!response.ok)throw new Error(item.error||'Upload failed');if(['clip','intro','outro'].includes(kind)&&!item.hasVideo)throw new Error('Please select a video.');if(['narration','music'].includes(kind)&&!item.hasAudio)throw new Error('Please select an audio file.');if(kind==='clip'){draft.clips=draft.clips||[];draft.clips.push({mediaId:item.id,name:item.name,start:0,duration:Math.min(item.duration,60),sourceDuration:item.duration});}else{draft[kind+'Id']=item.id;draft[kind+'Name']=item.name;}toast('Media saved. Configure it in Timeline.');if(page==='editor'&&editorTab==='timeline')editorFields();});mediaPending--;}
function makeTickerImage(){if(!draft.ticker)return null;const w=$('#canvas').width;const c=document.createElement('canvas'),x=c.getContext('2d');const font=Math.round(w*.019);x.font=`${font}px Arial`;c.width=Math.min(4096,Math.ceil(x.measureText(draft.ticker).width)+40);c.height=Math.ceil(font*1.7);x.font=`${font}px Arial`;x.fillStyle='white';x.textBaseline='middle';x.fillText(draft.ticker,10,c.height/2,c.width-20);return c.toDataURL('image/png');}

let otpChallenge=null;
function otpLogin(){if(offline)return toast('OTP needs the connected backend.');if(!config.capabilities?.otp)return toast('The administrator has not configured the SMS OTP service.');modal('Mobile OTP login',`<p class="muted">Use the same number each time. This creates a separate phone account unless you already have one.</p><form onsubmit="event.preventDefault();sendOtp()"><label for="otp-name">Your name</label><input id="otp-name" autocomplete="name" required><label for="otp-phone">Mobile number with country code</label><input id="otp-phone" type="tel" placeholder="+919876543210" autocomplete="tel" required><button class="primary full" style="margin-top:20px">Send OTP</button></form>`);}
async function sendOtp(){await run(async()=>{const name=$('#otp-name').value,phone=$('#otp-phone').value;const result=await api('/auth/otp/send','POST',{phone});otpChallenge={id:result.challengeId,name};modal('Verify your mobile',`<p>Enter the code sent to ${esc(phone)}.</p><form onsubmit="event.preventDefault();checkOtp()"><label for="otp-code">Verification code</label><input id="otp-code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{4,10}" required><button class="primary full" style="margin-top:20px">Verify and log in</button></form><small>Expires in 10 minutes. Maximum 5 attempts.</small>`);});}
async function checkOtp(){await run(async()=>{if(!otpChallenge)throw new Error('Request a new OTP.');const result=await api('/auth/otp/check','POST',{challengeId:otpChallenge.id,name:otpChallenge.name,code:$('#otp-code').value});otpChallenge=null;user=result.user;me=await api('/me');await sync();$('#dialog').close();render();toast('Mobile verified. Welcome to DMS NEWS.');});}

async function manageMedia(){if(!requireLogin())return;await run(async()=>{const items=await api('/media');modal('My uploaded media',`<p class="muted">Deleting removes the stored file. Media used in saved projects must be removed from those projects first.</p>${items.map(i=>`<div class="row between" style="padding:12px 0;border-bottom:1px solid var(--line)"><span>${esc(i.name)}<br><small>${i.duration.toFixed(1)} seconds</small></span><button class="small" data-id="${esc(i.id)}" onclick="deleteMedia(this.dataset.id)">Delete</button></div>`).join('')||'<p>No uploaded media yet.</p>'}`);});}
async function deleteMedia(id){if(JSON.stringify(draft).includes(id))return toast('Remove this media from the current timeline first.');if(!confirm('Permanently delete this uploaded media file?'))return;await run(async()=>{await api('/media/'+id,'DELETE');await manageMedia();});}

async function refreshCatalog(){if(offline)return toast("Offline preview uses its local catalog.");await run(async()=>{config=await api("/config");if(user){me=await api("/me");await sync();}render();toast("Latest templates and prices loaded.");});}

async function downloadExisting(url,format){await run(async()=>{if(!/^\/api\/files\/[a-f0-9-]+\.(png|jpg|mp4)$/.test(url))throw new Error("Invalid file");const r=await fetch(url);if(!r.ok)throw new Error("Download failed");downloadBlob(await r.blob(),"DMS-news."+format);});}
